### PR TITLE
chore: remove uuid from dependencies

### PR DESCRIPTION
**Pull request by a9a4k**
Getting an error when using wsgi

image

From this [SO post](https://stackoverflow.com/questions/33612977/how-to-use-uuid-lib-with-mod-wsgi) seems like it's not needed since python 2.5

### CODE REVIEW

**Review by Naapperas — APPROVED** [review]

**Comment by Naapperas** [comment]
@almeynman I approved the changes already but won't merge them just yet: the status checks are not running because I didn't enable the `pull_request` event in the CI files, so that is coming first.

Once that is fixed I'll get back to you.

**Comment by Naapperas** [comment]
> @almeynman I approved the changes already but won't merge them just yet: the status checks are not running because I didn't enable the `pull_request` event in the CI files, so that is coming first.
> 
> Once that is fixed I'll get back to you.

Done, please rebase with develop so we can merge.

**Comment by a9a4k** [comment]
@Naapperas done

**Comment by Naapperas** [comment]
> @Naapperas done

Merged! Thank you so much

**Pull request merged**
